#!/bin/bash
#MadeByShadowParrotVMX
#If u can't check, just try arping.

A=`timeout 1 ping -c 1 $1 | grep "64" | cut -d" " -f6 | cut -d"=" -f2` 

if [[ $A = "" ]] ; then
echo ""
echo "$(tput setaf 6)[*] Firewall up or Host down."
echo ""
exit
fi


if [[ $A -le 64 ]] ; then
echo ""
echo "$(tput setaf 6)[*] Linux."
echo ""
fi

if [[ $A -gt 64 ]] ; then
echo ""
echo "$(tput setaf 6)[*] Windows."
echo ""
fi
